use bitcoin::secp256k1::PublicKey;

use crate::bbqr::{self, KtFileType};
use crate::error::Error;

/// The `R` packet generated by the receiver.
/// Binary layout: 33 bytes = AES-256-CTR(SHA256(8-digit-code), compressed_pubkey).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReceiverPacket {
    /// The AES-encrypted compressed public key (33 bytes).
    encrypted_pubkey: [u8; 33],
}

impl ReceiverPacket {
    pub(crate) fn new(encrypted_pubkey: [u8; 33]) -> Self {
        Self { encrypted_pubkey }
    }

    pub(crate) fn encrypted_pubkey(&self) -> &[u8; 33] {
        &self.encrypted_pubkey
    }

    /// Encode as a single-frame BBQr `R` string.
    pub fn to_bbqr(&self) -> String {
        bbqr::encode(&self.encrypted_pubkey, KtFileType::Receiver)
    }

    /// Parse from a BBQr `R` string.
    pub fn from_bbqr(s: &str) -> Result<Self, Error> {
        let (ft, data) = bbqr::decode(s)?;
        if ft != KtFileType::Receiver {
            return Err(Error::InvalidReceiverPacket("expected R-type BBQr".into()));
        }
        let arr: [u8; 33] = data
            .try_into()
            .map_err(|_| Error::InvalidReceiverPacket("encrypted pubkey must be 33 bytes".into()))?;
        Ok(Self { encrypted_pubkey: arr })
    }

    /// Parse from raw bytes (33-byte encrypted pubkey).
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        let arr: [u8; 33] = bytes
            .try_into()
            .map_err(|_| Error::InvalidReceiverPacket("must be exactly 33 bytes".into()))?;
        Ok(Self { encrypted_pubkey: arr })
    }
}

/// The `S` packet generated by the sender.
/// Binary layout: sender_pubkey (33 bytes) || encrypted_body (variable).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SenderPacket {
    sender_pubkey: PublicKey,
    encrypted_body: Vec<u8>,
}

impl SenderPacket {
    pub(crate) fn new(sender_pubkey: PublicKey, encrypted_body: Vec<u8>) -> Self {
        Self { sender_pubkey, encrypted_body }
    }

    pub(crate) fn sender_pubkey(&self) -> &PublicKey {
        &self.sender_pubkey
    }

    pub(crate) fn encrypted_body(&self) -> &[u8] {
        &self.encrypted_body
    }

    /// Encode as a single-frame BBQr `S` string.
    pub fn to_bbqr(&self) -> String {
        let mut raw = self.sender_pubkey.serialize().to_vec();
        raw.extend_from_slice(&self.encrypted_body);
        bbqr::encode(&raw, KtFileType::Sender)
    }

    /// Parse from a BBQr `S` string.
    pub fn from_bbqr(s: &str) -> Result<Self, Error> {
        let (ft, data) = bbqr::decode(s)?;
        if ft != KtFileType::Sender {
            return Err(Error::InvalidSenderPacket("expected S-type BBQr".into()));
        }
        Self::from_bytes(&data)
    }

    /// Parse from raw bytes: sender_pubkey (33 bytes) || encrypted_body.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, Error> {
        if bytes.len() < 33 {
            return Err(Error::InvalidSenderPacket("too short (need ≥33 bytes)".into()));
        }
        let sender_pubkey = PublicKey::from_slice(&bytes[..33])
            .map_err(|e| Error::InvalidSenderPacket(format!("bad sender pubkey: {e}")))?;
        let encrypted_body = bytes[33..].to_vec();
        Ok(Self { sender_pubkey, encrypted_body })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use bitcoin::secp256k1::Secp256k1;

    #[test]
    fn receiver_packet_bbqr_roundtrip() {
        let encrypted = [0xABu8; 33];
        let pkt = ReceiverPacket::new(encrypted);
        let bbqr = pkt.to_bbqr();
        assert!(bbqr.starts_with("B$2R"));
        let recovered = ReceiverPacket::from_bbqr(&bbqr).unwrap();
        assert_eq!(pkt, recovered);
    }

    #[test]
    fn sender_packet_bbqr_roundtrip() {
        use rand::RngExt as _;
        let secp = Secp256k1::new();
        let mut bytes = [0u8; 32];
        rand::rng().fill(&mut bytes);
        let sk = bitcoin::secp256k1::SecretKey::from_slice(&bytes).unwrap();
        let pk = sk.public_key(&secp);
        let body = vec![0x11u8; 50];
        let pkt = SenderPacket::new(pk, body);
        let bbqr = pkt.to_bbqr();
        assert!(bbqr.starts_with("B$2S"));
        let recovered = SenderPacket::from_bbqr(&bbqr).unwrap();
        assert_eq!(pkt, recovered);
    }

    #[test]
    fn sender_packet_wrong_type_is_error() {
        let data = [0xBBu8; 33];
        let r_bbqr = bbqr::encode(&data, KtFileType::Receiver);
        assert!(SenderPacket::from_bbqr(&r_bbqr).is_err());
    }
}
