[bindings.swift]
cdylib_name = "coveutilffi"

[bindings.kotlin]
package_name = "org.bitcoinppl.cove.util"
cdylib_name = "coveutilffi"

[bindings.kotlin.external_packages]
cove_types = "org.bitcoinppl.cove.types"
cove_device = "org.bitcoinppl.cove.device"
cove_nfc = "org.bitcoinppl.cove.nfc"
cove_tap_card = "org.bitcoinppl.cove.tapcard"
