[bindings.kotlin]
package_name = "org.bitcoinppl.cove_core.tapcard"
cdylib_name = "tap_card"

[bindings.kotlin.external_packages]
cove_types = "org.bitcoinppl.cove_core.types"
cove_device = "org.bitcoinppl.cove_core.device"
cove_nfc = "org.bitcoinppl.cove_core.nfc"
cove_util = "org.bitcoinppl.cove_core.util"

[bindings.swift]
cdylib_name = "tap_card"
ffi_module_name = "tap_cardFFI"
omit_argument_labels = false
generate_module_map = true

