[bindings.swift]
cdylib_name = "covenfcffi"

[bindings.kotlin]
package_name = "org.bitcoinppl.cove.nfc"
cdylib_name = "covenfcffi"

[bindings.kotlin.external_packages]
cove_types = "org.bitcoinppl.cove.types"
cove_device = "org.bitcoinppl.cove.device"
cove_tap_card = "org.bitcoinppl.cove.tapcard"
cove_util = "org.bitcoinppl.cove.util"