[bindings.swift]
generate_module_maps = true
cdylib_name = "cove_types_ffi"

[bindings.kotlin]
package_name = "org.bitcoinppl.cove.types"
cdylib_name = "cove_types_ffi"

[bindings.kotlin.external_packages]
cove_device = "org.bitcoinppl.cove.device"
cove_nfc = "org.bitcoinppl.cove.nfc"
cove_tap_card = "org.bitcoinppl.cove.tapcard"
cove_util = "org.bitcoinppl.cove.util"

