[bindings.swift]
generate_module_maps = true
cdylib_name = "cove_types_ffi"

[bindings.kotlin]
package_name = "org.bitcoinppl.cove_core.types"
cdylib_name = "cove_types_ffi"

[bindings.kotlin.external_packages]
cove_device = "org.bitcoinppl.cove_core.device"
cove_nfc = "org.bitcoinppl.cove_core.nfc"
cove_tap_card = "org.bitcoinppl.cove_core.tapcard"
cove_util = "org.bitcoinppl.cove_core.util"

